### ISSUE TITLE
创建项目的dialog按enter键不提交

### ISSUE THREAD

**Issue by hit9** [eleme/banshee#180]
input和两个button未在一个表单中，所以我刚才尝试加type="submit" 也没用。。。

我想的办法是：搞到表单里，js拦截表单的submit事件，perventDefault，然后再post json. 这样type=submit也是可以用的

**Comment by hit9** [comment]
@facesea

**Comment by facesea** [comment]
@hit9 这样还不如直接绑个enter key事件触发提交方法简单？

**Comment by hit9** [comment]
舍本逐末啊…

**Comment by facesea** [comment]
这个UI框架下的dialog没办法整体嵌入到form表单里去，所以submit button难以用进去，dialog内部倒是好嵌一个form。

**Comment by hit9** [comment]
只要input和俩按钮在一个表单就可以啊 form不带样式又

发自我的 iPhone

**Comment by facesea** [comment]
两个action按钮是属于dialog的。。。

**Comment by hit9** [comment]
那这样 你先试下 不可以就算了…

发自我的 iPhone

**Comment by facesea** [comment]
不过可以用button的form属性来指定form，讲道理应该是可以的。

**Comment by facesea** [comment]
#183
