### ISSUE TITLE
Output channel is full, skipping..

### ISSUE THREAD

**Issue by hit9** [eleme/banshee#274]
@nrzipher 由于detector分析后只要匹配上filter通过的指标都会进入channel. alerter从channel接收到job后
会：对每个rule进行测试，测试成功则获取对应的project，然后对project的所有user执行command。

现在在没有真是警报出来的时候就发生了channel满的情况。

原因是：24个detector workers往一个channel发送数据，有4个alerter workers取数据。每次要遍历所有的规则，目前仅仅不到100个规则，导致alerter追不上队列。

我的解决办法想到的是：对metric加个field字段MatchedRule, filter匹配上后把匹配到的rule绑定到metric的这个属性上， 在alerter中对rule的测试只测试这一个rule.

**Comment by hit9** [comment]
该功能需要fileter那边实现。

**Comment by nrzipher** [comment]
其实看起来感觉应该不是filter这步骤卡住了alerter
应该是db没轮询的锅

**Comment by nrzipher** [comment]
我今天先把db轮询加上了再测试一下吧

**Comment by hit9** [comment]
嗯 db 轮询要加上。我觉得蛋疼的是还没有到报警的地步就开始查db了？

**Comment by nrzipher** [comment]
没。不报警的进不到db查询

**Comment by hit9** [comment]
我觉得就算查数据库，报警的那点量不足以拖垮

**Comment by nrzipher** [comment]
或者直接在Detector里面判断是否需要报警 不报警的不丢进output了

**Comment by hit9** [comment]
@nrzipher  可以. 在detector主循环里迭代下matched rules.

**Comment by hit9** [comment]
@nrzipher 按这个思路来个PR吧

**Comment by nrzipher** [comment]
好

**Comment by hit9** [comment]
Fixed in #289 #290  #283 .
