### ISSUE TITLE
添加 slack 集成.

### ISSUE THREAD

**Issue by wooparadog** [eleme/banshee#280]
@pingliu

**Comment by wooparadog** [comment]
需要:

1. alert to slack
2. mention team name. (wait for confirmation...)

**Comment by hit9** [comment]
Hmm 由于目前只支持email和短信，slack账户的信息没有存.. 需要讨论。。

**Comment by wooparadog** [comment]
第一版不用mention人…

**Comment by wooparadog** [comment]
添加几个需求

1, mention 机器人 能够返回指标截图-待定
2, 报警项目可以关联一个网址，能够直接从报警点到dashboard

**Comment by hit9** [comment]
https://godoc.org/github.com/eleme/banshee/alerter#hdr-Alert_To_Slack_Or_HipChat
