### ISSUE TITLE
ability to snooze alarm by project

### ISSUE THREAD

**Issue by ritksm** [eleme/banshee#377]
we need a feature that admin can snooze all alarms for a project within a certain time range

a pattern scope snooze would be even better

**Comment by hit9** [comment]
免打扰将只适用于短信

**Comment by hit9** [comment]
有需要关闭所有吗

**Comment by ritksm** [comment]
有需求的，如果没用的报警其实email也可以不发。。

**Comment by hit9** [comment]
这样：对项目提供一个一天内的静音时间段的配置可以吗
