### ISSUE TITLE
空值报警的需求

### ISSUE THREAD

**Issue by hit9** [eleme/banshee#482]
一个暴力的办法：每隔一段时间去check所有关心空值报警的规则的指标是否最新。

**Comment by hit9** [comment]
一个时间上不暴力的方法：

所有关心空值报警规则的指标放入一个小根堆，comparator是最后流入的时间。每次检查从堆定往下找直到流入时间和当前时间近乎一致为止。

嗯，也可以用个有序的结构比如skiplist(比数组更适合局部更新), 每次顺序检查直到最近流入时间不过期的指标为止。

@wooparadog

**Comment by hit9** [comment]
一个问题是:

1. 规则的添加和删除，以及指标的更新会对这个结构造成O(N)的遍历.

**Comment by wooparadog** [comment]
人为操作产生的 O(N) 其实还能接受的. 我们 count 类型应该有一半左右吧? 内存走一遍应该也不慢.
