### ISSUE TITLE
同类型报警信息的唯一ID

### ISSUE THREAD

**Issue by admon** [eleme/banshee#587]
同类型报警的样例：

> banshee-bot BOT [4:19 PM]  
> Website:***接口
> {高等级 16:19:25 Website:**.api f01fad1} 购物车 check*_cart 接口响应时间(mean_90)较往日同时段增加 当前值247.71毫秒, 历史平均值225.98毫秒
> 
> Website:***接口
> {高等级 16:19:25 Website:**.api dfd8822} 购物车 check*_cart 接口响应时间(mean_90)较往日同时段增加 当前值423.03毫秒, 历史平均值242.36毫秒 grafana图表 调整规则 

同一个接口的同类型报警，其中的Uniq ID（这里的 zhf01fad1 和 dfd8822）应该是一致的，便于导入到事件管理平台中。

**Comment by hit9** [comment]
@wooparadog 你来看下吧，这是个需求设计上的问题

**Comment by wooparadog** [comment]
@hit9 给他们加上一个 rule_id 就好了...

{高等级 16:19:25 Website:.api rule_id dfd8822}

**Comment by wooparadog** [comment]
加上了 id.
