### ISSUE TITLE
能否对接Prometheus的数据

### ISSUE THREAD

**Issue by wkshare** [eleme/banshee#596]
http://prometheus.io

有意愿提交PR，能给些指引，如何接入

**Comment by wooparadog** [comment]
https://github.com/eleme/banshee#network-protocol This is the input protocol. 

But we're not planning to support data sources other than statsd yet.

**Comment by wayslog** [comment]
Maybe you @wkshare  should think about convert prometheus protocol to **graphite protocol**  , which is simple and easy to be transformed .

**Comment by wkshare** [comment]
编码能力较弱，我自己试试先：） @wooparadog @wayslog
