### ISSUE TITLE
web-app doc does not match code. impossible to create a project?

### ISSUE THREAD

**Issue by fuzzyami** [eleme/banshee#621]
hey guys. thanks for your efforts. been trying to make this work.

it appears that this file -  https://github.com/eleme/banshee/blob/master/docs/web-api.md - does not match the actual code. perhaps it would be a good idea to update it or place a warning at the top about it.

specifically: one must create a team before a project can be created (and not as stated in the doc).

**Comment by zhaojkun** [comment]
@fuzzyami The document is somewhere outdated. I will update it soon.
