### ISSUE TITLE
Redirecting alerts

### ISSUE THREAD

**Issue by BorisWolfsoul** [eleme/banshee#622]
Is possible send alerts to a log file?

**Comment by fuzzyami** [comment]
@BorisWolfsoul it appears this can be done by using the alert-command:
`alerter:
    # Command to be executed to send alert messages, default: ""
    # Example: "python sender.py"
    # Reference: https://godoc.org/github.com/eleme/banshee/alerter
    command: ""

`

just write a simple python script to write to a local file. lmk if you need help with that.

**Comment by zhaojkun** [comment]
@BorisWolfsoul  Just like @fuzzyami mentioned. You can specify alert command in the [config file](https://github.com/eleme/banshee/blob/master/config/exampleConfig.yaml#L112).All information about   one event will be encoded as a JSON string and will be passed to the alert command as a command parameter.

**Comment by fuzzyami** [comment]
@BorisWolfsoul I've delved a little deeper into this:
1. you need to setup a receiver and associate it with a project. this is easily done via the web-app.
2. once an alert is called, banshee calls a command (which you customize - its basically a bash command - ) and the details about your receiver are passed to your command as a json struct

so you can set "python myscript.py" as your command and make sure that python script can parse the json, and voila: you're in control. your python script can either email or just log to file or whatever.

its a little convoluted, but also powerful.
see the example provided in Banshee's code, at alerter/exampleCommand/echo.go (its a go program)
