### ISSUE TITLE
Metrics periodicity: specifying "same day last week"

### ISSUE THREAD

**Issue by fuzzyami** [eleme/banshee#625]
hey guys,
The metrices I wish to track exhibit periodicity that isn't 'daily', but rather weekly - All sundays are similar, all mondays are similar etc.

can Banshee be configured to track that pattern?

**Comment by zhaojkun** [comment]
You can change the [period](https://github.com/eleme/banshee/blob/master/config/exampleConfig.yaml#L7) in the configuration file.

**Comment by fuzzyami** [comment]
Thanks - yes I've read the config file. 
I think the default values are set to compare daily trends - 
meaning "compare today to yesterday and the day before it etc".

but how do i specify "compare this Sunday to previous Sunday, this Monday to previous Monday"?

I think that if I set banshee's periodicity to "one week" it would look for weekly trends - which is NOT what I need. I needs week-days trends.

**Comment by zhaojkun** [comment]
I think you can change period and filter_offset both.The data distribution over filter_offset*period is considered as a gaussian distribution.So you can try to set period to seconds of a week,and filter_offset is 0.14 (1/7) ,also other values in the configuration should be fine tuned.

**Comment by fuzzyami** [comment]
thanks! i think that's what i wanted.
