### ISSUE TITLE
关于bashee使用的一些问题

### ISSUE THREAD

**Issue by gedennis** [eleme/banshee#634]
你好，目前我是使用statsd + banshee来监测一些metrics。但是使用的过程中有几个疑惑的地方。
## 邮件和短信报警未生效。
我对metric设置了阈值报警。![image](https://cloud.githubusercontent.com/assets/21010353/22133061/f18bccfa-def8-11e6-8f2e-8d7ac5d5e291.png)。然而指标已经超过了200。仍然没有产生报警。
## metric 图的渲染问题
这个metric图显示的很不清楚，有颜色重影，请问是不是渲染有问题。
![image](https://cloud.githubusercontent.com/assets/21010353/22133159/a3847ac4-def9-11e6-96bf-c8fa7ca3050d.png)
## 不连续指标的score计算
我的数据是1min上报，我分别使用timer和gauge，使用timer时虽然有指标超过阈值的情况，但是score一直为0。我也查过issue中关于score的描述，但还是不太清楚。能否解释下这个score？
望解答。

**Comment by zhaojkun** [comment]
1. 没有产生报警是不是因为没有添加待通知的用户造成的，查看下`项目`页面中的`历史告警`部分，那里边能看到该项目中所有规则产生的告警
2.  渲染问题，我需要再确认下
3. score的计算与阈值的设定无关，它反映的是当前值的波动情况。如果`score>0`说明当前值处于上升趋势，反之为下降趋势。如果`score>1`就会触发`趋势上升告警`的规则设定，如果`score<-1`，则触发`趋势下降告警`的规则

**Comment by gedennis** [comment]
谢谢你的解答，但仍有几处不惑之处。
## 邮件和短信报警问题
这个我确定在项目下的receiver中添加了接收人，但是没收到邮件和短信报警。对于历史告警，当下看是没有的，隔了很久才看到有，是不是有较大的时延？
## 不连续指标问题
对于score的计算，是算一种trend。那对于不连续指标是怎么算的呢。因为我相同的数据上报（1min一上报）现象上gauge确实会有score值，而timer始终为0。

**Comment by zhaojkun** [comment]
## 邮件和短信报警问题
1. 具体的邮件及短信报警，需要使用者在通知脚本中自己实现。可参考https://github.com/eleme/banshee/issues/622 。banshee会通过命令行参数的方式将event的所有数据传递给脚本。
2. 正常情况下，不会有太大的延时，对指标数据的检测还是很快的。你可以在webapp的`健康信息`中查看各种耗时。
3. 当前默认配置文件中设定 [alert_check_interval](https://github.com/eleme/banshee/blob/master/docker/config.yaml#L129)为60s，[notify_after](https://github.com/eleme/banshee/blob/master/docker/config.yaml#L129)为1。这两个配置项的意思是60s内发生一次event之后，再发现有event出现才会告警，即60s内发生两次event才会告警（具体为：将event保存到数据库中以便能在webapp上查看到，执行告警脚本等）。而你的数据正好是1min一个数据点，
默认设定情况下，两分钟的数据都是异常才会产生告警，可能就是你指的时延。可以对这两个配置项进行适当的调整，观察下是不是这里的问题。
## 不连续指标问题
对不连续指标计算score是没有意义的，但是banshee也会尝试对其进行计算，由用户设定的规则来决定是否使用对应的score值。
在banshee中gauge指标跟timer指标是一样的，并不会根据指标数据在statusd中的意义对其做特殊的处理，同时banshee的上游不局限于statusd,只要遵循banshee的数据协议就行。
score值始终为零，一种可能性是在计算score值的时间窗口中，数据量太少。在配置文件中可以通过设定 [filter_offset](https://github.com/eleme/banshee/blob/master/docker/config.yaml#L37)来调整时间窗口，通过设定 [least_count](https://github.com/eleme/banshee/blob/master/docker/config.yaml#L48)来调整score计算时需要的最少数据量。如果是这里的问题，建议适当调整`filter_offset`

**Comment by gedennis** [comment]
@zhaojkun 感谢你详尽的解答。I`ll close the issue.
