### ISSUE TITLE
关于不报警的疑问，以及报数据解析错误。

### ISSUE THREAD

**Issue by eueuy** [eleme/banshee#650]
banshee非常贴合我们的需求。
但是在使用中有几点不太明白。

# 1.报错问题
首先是使用中banshee日志会有很多
^[[31mERROR 2017-08-09 19:52:25 detector/detector.go:105^[[0m parse error timer.mean_90.timer.sssync.10_201_3_33.-ver-partial-commit.responseTime 1502279545  : detector: invalid protocol input, skipping..

我看了下源码发现statsd里遇到timer会一次传2个值给banshee, 分别是 mean_90 和 count_ps。类似于：
key1,timstamp,val,key2,timestamp2,val2 一共6个值，用逗号分隔。
但是banshee 的 detector.go 里却判断如果传过来的值进行split后不能大于3（也就是必须一个值），否则报错。 我在statsd端将 count_ps 去掉只传 mean_90 后报错消失 。 我这样做有什么影响？ 正确的解决方案是什么呢。

# 2.不报警问题
在使用中我为了测试触发报警， 人为压测制造大访问量。 之后观察指标图，发现指标的名字变成红色了 ，图上也有红色的区域。 应该是检测到了， 但是在项目的历史告警页里没发现任何告警事件。  我的报警条件是 trend ↑ || trend ↓ 。 配了项目组和项目，项目下也关联了人。空值报警是能看到的，但是我无论如何压测（持续>1m）都没有除了空值报警外的报警。

# 3.感谢劳动， 希望能得到帮助

**Comment by zhaojkun** [comment]
1. 报错问题 
statsd 这部分发送数据的时候，是将 `mean_90`与`count_ps` 两行进行发送的，能否你在`statsd`这边打印下日志，看下具体发送的数据是怎样的。
2. 不报警问题
确认下是不是没有配置相应的[alert command](https://github.com/eleme/banshee#alert-command)

**Comment by eueuy** [comment]
@zhaojkun 
感谢回复。
报错的statsd数据我稍后发上来。

报警问题，我是没有配命令脚本， 但是历史报警那个页面里应该有报警记录是否才是正常的？因为有空值报警的事件在里面。

**Comment by eueuy** [comment]
问题已经解决

我发现statsd 有概率发送val 为空的指标给banshee，这种情况下banshee会解析错误，并且不知为何报警判断也受到影响。 我在statsd的插件中增加了判断，如果为空就不发这条metric给banshee，报警也正常了。

有过有人遇到同样问题可以参考。我fork了一个分支，如果需要可以merge。
