### ISSUE TITLE
明显应该报警的曲线没有报警

### ISSUE THREAD

**Issue by eueuy** [eleme/banshee#653]
![image](https://user-images.githubusercontent.com/20703109/29207760-eab81c6a-7eb9-11e7-974f-66a0edf5f62c.png)

![image](https://user-images.githubusercontent.com/20703109/29208070-1e55acbc-7ebb-11e7-9e14-31c0afe5815d.png)

在这样的情况下居然始终未触发任何关于该指标的报警，包括debug日志和l历史告警页面 ：（
是我有什么认知上的错误吗？

**Comment by hitzzc** [comment]
我怀疑是时序上点的密度不够。
算法应该是取得 0.01*period (period在配置里配的是1天)的均值和方差，然后计算多个period，然后取联合方差，从而进行异常点识别的。
所以从你的折线图上来看，一是点的密度不够（0.01*period实际没多长），另外异常点检测是对周期性metric做检测，可能要放到N天去看待你的这个突出的折线是否是异常

**Comment by zhaojkun** [comment]
@eueuy 就像 @hitzzc  提到的，
时序点的密度不够的原因。默认的时间间隔是10s一个点（这里与statsd保持了一致）。可以通过调整时间间隔的参数来适配你们的环境，从图上看你们的数据应该是5分钟一个点。
同时还有个参数需要注意，示例配置文件中，`least_count` 为30。意思是至少有30个点才会真正的执行异常值检测算法。从图上看，可能数据点不够

**Comment by eueuy** [comment]
@zhaojkun @hitzzc 
我们的时间间隔也是10s ，图上是一天的做了压缩。目前在测试环境跑有可能点不够，因为量时有时无。下周放生产环境测试一下。

**Comment by eueuy** [comment]
确实是duration不够的问题。
